### ISSUE TITLE
VisionSubsystem.cpp with symbol "camera" and "GetImage"

### ISSUE THREAD

**Issue by GabrielCiolac** [frc1334/RecycleRush2015#1]
The IDE is claiming that GetImage doesn't exist even though it's clearly displayed in the WPILib in "AxisCamera.h". Also "camera" isn't being recognized on the same line as the .GetImage issue. This only applies to the latest commit (commit # 76a78eea3e33bebc15d959a1f112df349c8a08a7 ) Will take down issue once fixed.

**Comment by Megapead** [comment]
Closing Issue due to self stupidity

**Comment by GabrielCiolac** [comment]
Opened again because didn't check solution before declaring it as the solution.

**Comment by JamieSinn** [comment]
https://github.com/frc1334/RecycleRush2015/blob/master/src/Subsystems/CameraSubsystem.cpp#L14

See how I did it.

Pointers are needed when you create the variable as a pointer.
https://github.com/frc1334/RecycleRush2015/blob/master/src/Subsystems/VisionSubsystem.h#L16

Camera->GetImage() Will work
